version: '3.8'

services:
  nest-api:
    container_name: nest-api-dev
    build:
      context: .
      dockerfile: Dockerfile-api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: npm run start:dev
