# Dockerfile-api

FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Expõe a porta padrão do NestJS
EXPOSE 3000

# Usa ts-node ou nest para desenvolvimento
CMD ["npm", "run", "start:dev"]
